config/routes.rb
Rails.application.routes.draw do
  root "atm_machines#index"
  resources :atm_machines
  resources :transactions
  resources :user_infos
  resources :accounts do
    member do
      get :new_deposit
      post :create_deposit
      get :new_withdrawal
      post :create_withdrawal
    end
  end
  
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  devise_scope :user do
  get 'sign_in', to: 'devise/sessions#new'
end

end

app/models/user_info.rb
class UserInfo < ActiveRecord::Base
    #attr_accessible :user_id , :name , :image
    belongs_to :user
    validates :first_name, :last_name, :phone_number, :presence => true
    after_create :create_account
    mount_uploader :image, ImageUploader
    #validates_format_of :image, :with => %r{\.(jpg|jpeg)$}i, :message => "Only JPG Format"
    validate :image_size_validation

    private
    def create_account
        Account.create(user_id: user_id, balance: 0.0)
    end 
         def image_size_validation
    errors[:image] << "should be less than 5MB" if image.size > 5.megabytes
  end
  end

app/controllers/user_infos_controller.rb
class UserInfosController < ApplicationController
  before_action :set_user_info, only: [:show, :edit, :update, :destroy]

  # GET /user_infos
  # GET /user_infos.json
  def index
    @user_infos = UserInfo.all
  end

  # GET /user_infos/1
  # GET /user_infos/1.json
  def show
  end

  # GET /user_infos/new
  def new
    session[:atm_id] = params[:atm_info]
    @user_info = UserInfo.new
  end

  # GET /user_infos/1/edit
  def edit
    session[:atm_id] = params[:atm_info]
  end

  # POST /user_infos
  # POST /user_infos.json
  def create
    @user_info = UserInfo.new(user_info_params)
    
    respond_to do |format|
      if @user_info.save
        format.html { redirect_to atm_machine_path(session[:atm_id])}
        format.json { render :show, status: :created, location: @user_info }
      else
        format.html { render :new }
        format.json { render json: @user_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_infos/1
  # PATCH/PUT /user_infos/1.json
  def update
    respond_to do |format|
      if @user_info.update(user_info_params)
        format.html { redirect_to atm_machine_path(session[:atm_id])}
        format.json { render :show, status: :ok, location: @user_info }
      else
        format.html { render :edit }
        format.json { render json: @user_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_infos/1
  # DELETE /user_infos/1.json
  def destroy
    @user_info.destroy
    respond_to do |format|
      format.html { redirect_to user_infos_url, notice: 'User info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_info
      @user_info = UserInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_info_params
      params.require(:user_info).permit(:first_name, :last_name, :email, :phone_number, :user_id , :image)
    end
end

app/helpers/user_infos_helper.rb
module UserInfosHelper
end

app/views/user_infos/_form.html.erb
<div class="container">
<img src=http://a.dryicons.com/images/icon_sets/shine_icon_set/png/256x256/user_info.png width="150" height="150">
<%= form_for @user_info,:html => {:multipart => true} do |f| %>
  <% if @user_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_info.errors.count, "error") %> prohibited this user_info from being saved:</h2>

      <ul>
      <% @user_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  </p>
          <p>
      <%= f.file_field :image, onchange: "validateFiles(this);",
    data: { max_file_size: 5.megabytes } %>
   </p>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>
 

app/views/user_infos/edit.html.erb
<div class="container">

<h1><font color="red">Editing User Info</font></h1>
<%= render 'form' %>

&nbsp;&nbsp;&nbsp;<%= link_to 'Show', @user_info , class:"btn btn-info" %> |
<%= link_to 'Back', atm_machine_path(session[:my_atm]),class:"btn btn-danger" %>
</div>

app/views/user_infos/index.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

<h1>Listing User Infos</h1>

<table class= "table table-striped">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_infos.each do |user_info| %>
      <tr>
        <td><%= user_info.first_name %></td>
        <td><%= user_info.last_name %></td>
        <td><%= user_info.email %></td>
        <td><%= user_info.phone_number %></td>
        <td><%= link_to 'Show', user_info ,class:"btn btn-primary" %></td>>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', atm_machine_path(session[:my_atm]),class:"btn btn-danger" %>
</div>

app/views/user_infos/new.html.erb
<div class="container">

   <h1>New User Info</h1>

<%= render 'form' %>

<%= link_to 'Back', user_infos_path %>
</div>

app/views/user_infos/show.html.erb
<div class="container">

<p id="notice"><%= notice %></p>
 
 <p>
  
<strong>Person Picture:</strong><br>
  <%= image_tag @user_info.image_url(:thumb), class:"img-thumbnail" if @user_info.image? %>
  
</p>
<p>
  <strong>First name:</strong>
  <%= @user_info.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user_info.last_name %>
</p>
 

 
<p>
  <strong>Phone number:</strong>
  <%= @user_info.phone_number %>
</p>



<%= link_to 'back', atm_machine_path(session[:my_atm]) ,class:"btn btn-danger" %>

</div>