config/routes.rb
Rails.application.routes.draw do
  root "atm_machines#index"
  resources :atm_machines
  resources :transactions
  resources :user_infos
  resources :accounts do
    member do
      get :new_deposit
      post :create_deposit
      get :new_withdrawal
      post :create_withdrawal
    end
  end
  
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  devise_scope :user do
  get 'sign_in', to: 'devise/sessions#new'
end

end

app/models/atm_machine.rb
class AtmMachine < ActiveRecord::Base
   geocoded_by :address
   after_validation :geocode
    has_many :transactions
   # reverse_geocoded_by :latitude, :longitude, :address => :atm_machine
    #after_validation :reverse_geocode
   #  validates :address, :presence => true
end

app/controllers/atm_machines_controller.rb
class AtmMachinesController < ApplicationController
  before_action :set_atm_machine, only: [:update, :destroy]
  skip_before_filter :authenticate_user!, :only => :index
  
def index
 
  if params[:search].present?
    @atm_machines = AtmMachine.near(params[:search], 50)
  else
    @atm_machines = AtmMachine.all
  end
end
  
  def show
    @atm_machine = AtmMachine.find(params[:id])
    @user = User.find(current_user)
    session[:my_atm]=@atm_machine.id
    
  end

  # GET /atm_machines/new
  def new
    @atm_machine = AtmMachine.new
  end

  # GET /atm_machines/1/edit
  def edit
    @atm_machine = AtmMachine.find(params[:id])
  end

  # POST /atm_machines
  # POST /atm_machines.json
  def create
    @atm_machine = AtmMachine.new(atm_machine_params)

    respond_to do |format|
      if @atm_machine.save
        format.html { redirect_to @atm_machine, notice: 'Atm machine was successfully created.' }
        format.json { render :show, status: :created, location: @atm_machine }
      else
        format.html { render :new }
        format.json { render json: @atm_machine.errors, status: :unprocessable_entity }
      end
    end
end

  # PATCH/PUT /atm_machines/1
  # PATCH/PUT /atm_machines/1.json
  def update
    respond_to do |format|
      if @atm_machine.update(atm_machine_params)
        format.html { redirect_to @atm_machine, notice: 'Atm machine was successfully updated.' }
        format.json { render :show, status: :ok, location: @atm_machine }
      else
        format.html { render :edit }
        format.json { render json: @atm_machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /atm_machines/1
  # DELETE /atm_machines/1.json
  def destroy
    @atm_machine.destroy
    respond_to do |format|
      format.html { redirect_to atm_machines_url, notice: 'Atm machine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_atm_machine
      @atm_machine = AtmMachine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def atm_machine_params
      params.require(:atm_machine).permit(:address, :latitude, :longitude)
    end
end

app/helpers/atm_machines_helper.rb
module AtmMachinesHelper
end

app/views/atm_machines/_form.html.erb
<div class="container">
<%= form_for(@atm_machine) do |f| %>
  <% if @atm_machine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@atm_machine.errors.count, "error") %> prohibited this atm_machine from being saved:</h2>

      <ul>
      <% @atm_machine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>

  </div>
  <div class="actions">
    <%= f.submit  %>
  </div>
<% end %>
</div>

app/views/atm_machines/edit.html.erb
<div class="container">
<h1>Editing Atm Machine</h1>

<%= render 'form' %>

<%= link_to 'Show', @atm_machine %> 
<%= link_to 'Back', atm_machines_path %>
</div>

app/views/atm_machines/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  
 <center><img src=http://www.affordablecebu.com/pictures/articles/banking/Deposit_money_in_Unionbank_ATM.gif width="350" height="350"></center>
<center><h1>Listing Atm Machines</h1></center>

<center><%= form_tag atm_machines_path, :method => :get do %></center>
  <p>
    <center><%= text_field_tag :search, params[:search] %></center><br>
    <center><%= submit_tag "Search Near", :name => nil %></center>
  </p>
<% end %>

<table class= "table table-striped">
  <thead>
    <tr>
     <th>ATM Machine Number</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @atm_machines.each do |atm_machine| %>
      <tr>
       <td><%= atm_machine.id%></td>
        <td><%= atm_machine.address%></td>
        <td><%= link_to 'Show', atm_machine , class:"btn btn-danger" %></td> 
 
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Atm machine', new_atm_machine_path, class:"btn btn-primary btn-lg btn-block" %>

</div>

app/views/atm_machines/new.html.erb
<div class="container">
<h1><font color="blue">New Atm Machine</font></h1>
<%= render 'form' %>

&nbsp;&nbsp;&nbsp;<%= link_to 'Back', atm_machines_path,class:"btn btn-danger" %>
</div>

app/views/atm_machines/show.html.erb
<div class="container">

<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@atm_machine.latitude}%2C#{@atm_machine.longitude}" %>

<h3>Nearby atm_machines</h3>
<ul>
 <% for atm_machine in @atm_machine.nearbys(10) %>
  <li><%= link_to atm_machine.address, atm_machine %> (<%= atm_machine.distance.round(2) %> miles)</li>
<% end %>
</ul>
<% if current_user.user_info.present? %>
    <%= link_to 'Edit user info', edit_user_info_path(current_user.user_info, atm_info: @atm_machine.id),class:"btn btn-info" %>
<%else%>
    <%= link_to 'Add user info', new_user_info_path(atm_info: @atm_machine.id) %>
<%end%>

<% if current_user.account.present? %>

<%= link_to 'Deposit', new_deposit_account_path(current_user.account),class:"btn btn-success" %>
<%= link_to 'Withdrawal' , new_withdrawal_account_path(current_user.account),class:"btn btn-primary" %>
<%= link_to 'Transactions', transactions_path(account_id: current_user.account.id),class:"btn btn-warning"%>
<h1>Total Balance => <%= number_to_currency(current_user.account.balance) %></h1>
<p><%= params[:msg]%></p>
<%end%><br>
<br>
<%= link_to 'back', atm_machines_path,class:"btn btn-danger"%>
</div>