config/routes.rb
Rails.application.routes.draw do
  root "atm_machines#index"
  resources :atm_machines
  resources :transactions
  resources :user_infos
  resources :accounts do
    member do
      get :new_deposit
      post :create_deposit
      get :new_withdrawal
      post :create_withdrawal
    end
  end
  
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  devise_scope :user do
  get 'sign_in', to: 'devise/sessions#new'
end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
     @transactions = Transaction.where(account_id: params[:account_id])
   
      respond_to do |format|
      format.html
      format.csv { send_data @transactions.to_csv }
     
      
  end
end
end



  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:transaction_no, :transaction_type, :amount, :account_id)
    end
  

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<div class="container">
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :transaction_no %><br>
    <%= f.text_field :transaction_no %>
  </div>
  <div class="field">
    <%= f.label :transaction_type %><br>
    <%= f.number_field :transaction_type %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/transactions/edit.html.erb
<div class="container">
<h1>Editing Transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> 
<%= link_to 'Back', transactions_path %>
</div>

app/views/transactions/index.csv.erb
<table border="1">
   <tr>
      <th>ATM</th>
      <th>Amount</th>
      <th>Transaction type</th>
      <th>Transaction Time</th>
     </tr>
     <% @transactions.each do |transaction| %>
     <tr>
          <td><%= transaction.atm_machine_id %></td>
        <td><%= transaction.amount %></td>
        <td><% transaction.transaction_type%></td>
        <td><%= transaction.created_at%></td>
     </tr>
     <% end %>
     </table>

app/views/transactions/index.html.erb
<div class="container">
  
<p id="notice"><%= notice %></p>
<h1>Listing Transactions</h1>
<p>
    Download:
    <%= link_to "Transactions.csv" , transactions_path(account_id: params[:account_id],format: "csv") %>
   
</p>
<table class="table table-striped", id= 'myTable'>
  <thead>
    <tr>
      <th>ATM</th>
      <th>Amount</th>
      <th>Transaction type</th>
      <th>Transaction Time</th>
     
    </tr>
  </thead>

  <tbody>
   <% @transactions.each do |transaction| %>
   
     <tr>
        <td><%= transaction.atm_machine_id %></td>
        <td><%= transaction.amount %></td>
        <td><% if transaction.transaction_type ==1 %>
           <%="Deposit"%>
           <%else%>
           <%="Withdrawal"%>
           
           <%end%></td>
           <td><%=transaction.created_at.in_time_zone('Central Time (US & Canada)')%></td>
         
     </tr>
    <% end %>
  </tbody>
  
 </table>
<%= link_to 'Back', atm_machine_path(session[:my_atm]),class:"btn btn-danger" %>

</div>

app/views/transactions/new.html.erb
<div class="container">
<h1>New Transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>
</div>

app/views/transactions/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Transaction no:</strong>
  <%= @transaction.transaction_no %>
</p>

<p>
  <strong>Transaction type:</strong>
  <%= @transaction.transaction_type %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @transaction.amount %>
</p>


<%= link_to 'Back', transactions_path,class:"btn btn-primary btn-sm" %>
</div>