config/routes.rb
Rails.application.routes.draw do
  root "atm_machines#index"
  resources :atm_machines
  resources :transactions
  resources :user_infos
  resources :accounts do
    member do
      get :new_deposit
      post :create_deposit
      get :new_withdrawal
      post :create_withdrawal
    end
  end
  
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  devise_scope :user do
  get 'sign_in', to: 'devise/sessions#new'
end

end

app/models/account.rb
class Account < ActiveRecord::Base
    belongs_to :user
    has_many :transactions, dependent: :destroy
    #validates_presence_of :user_id
    attr_accessor :amount
    #validates :balance, :numericality => { greater_than_or_equal_to: 0 }
    # validates :account_no, :balance, :presence => true
    
    def deposit (amt)
      if amt[:amount].to_f <= 0.0 || limit_daily_deposit?(amt[:amount])
        errors.add(:amount, "Maximum Daily Desposit $1000")
        return false
      else
        self.balance = self.balance.to_f + amt[:amount].to_f
        self.save
        return true
      end
    end

  def withdrawal (amt)
      if amt[:amount].to_f <= 0.0 || max_withdrawal?(amt[:amount])
        errors.add(:amount, "Maximum Daily Withdrawal $500")
        return false
    else
        self.balance = self.balance.to_f - amt[:amount].to_f
        self.save
        return true
      end
   end

private

def limit_daily_deposit?(current_amount)
    amounts_list = self.transactions.today.where(transaction_type: 1).pluck(:amount)
    sum = amounts_list.map(&:to_f).reduce(:+)
    new_balance_today = sum.to_f + current_amount.to_f
    if new_balance_today > 1000
        return true
    else
        false
    end
end

    
 def max_withdrawal?(current_amount)
    amounts_list = self.transactions.today.where(transaction_type: 2).pluck(:amount)
    sum = amounts_list.map(&:to_f).reduce(:+)
    new_balance_today =  current_amount.to_f + sum.to_f 
    if new_balance_today > 500
        return true
    else
        false
    end
end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  
  def new_deposit
    @account = Account.find(params[:id])
  end
  
  def create_deposit
    @account = Account.find(params[:id])
    if deposit_params[:amount].to_f <= 1000 && deposit_params[:amount].to_f > 0 && @account.deposit(deposit_params)
      @account.transactions.create(amount: deposit_params[:amount],atm_machine_id: session[:my_atm], transaction_type: 1)
      flash[:notice] = " Deposit Complete Successfully"
      redirect_to atm_machine_path(session[:my_atm])  
   else
     if deposit_params[:amount].to_f > 1000
      flash[:alert] = "Your Maximum Daily Deposit $1000"
     elsif @account.errors.any?
     flash[:alert]=@account.errors.full_messages.to_sentence
   else
     flash[:alert] = "Please Enter A Valid Amount"
   end 
      render :new_deposit
    end
end 


  def new_withdrawal
    @account = Account.find(params[:id])
  end
  
  def create_withdrawal
    @account = Account.find(params[:id])
    if withdrawal_params[:amount].to_f <= 500 && withdrawal_params[:amount].to_f > 0 && withdrawal_params[:amount].to_f <= @account .balance && @account.withdrawal(withdrawal_params)
    @account.transactions.create(amount: withdrawal_params[:amount],atm_machine_id: session[:my_atm], transaction_type: 2)
    flash[:notice] = "Transaction Complete… did you want to perform another transaction?"
    redirect_to atm_machine_path(session[:my_atm])
  else
     if withdrawal_params[:amount].to_f > 500
      flash[:alert] = "Your Maximum Daily Withdrawal $500"
     elsif @account.errors.any?
      flash[:alert] =@account.errors.full_messages.to_sentence
      else
        flash[:alert] = "Please Enter A Valid Amount"
      end
    render :new_withdrawal
end 
end

  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:account_no, :balance, :user_id)
    end
    
    def deposit_params
        params.require(:account).permit(:amount)
    end
    def withdrawal_params
      params.require(:account).permit(:amount)
    end
  end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<div class="container">
<%= form_for(@account) do |f| %>

  <div class="field">
    <%= f.label :account_no %><br>
    <%= f.text_field :account_no %>
  </div>
  <div class="field">
    <%= f.label :balance %><br>
    <%= f.text_field :balance %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/accounts/edit.html.erb
<div class="container">
<h1>Editing Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>
</div>

app/views/accounts/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Listing Accounts</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Account no</th>
      <th>Balance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.account_no %></td>
        <td><%= account.balance %></td>
        <td><%= link_to 'Show', account,class:"btn btn-info" %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', atm_machine_path(session[:my_atm]),class:"btn btn-danger" %>
</div>

app/views/accounts/new.html.erb
<div class="container">
<h1>New Account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>
</div>

app/views/accounts/new_deposit.html.erb
<div class="container">
 <img src=http://www.citradesreview.com/wp-content/uploads/2014/02/deposit.jpg width="300" height="300">
  <%= form_for @account, url: create_deposit_account_path, method: :post do |f| %>
  <div class="field">
   <h1><%= f.label "Add Amount" %></h1><br>
   <%= f.text_field :amount %>
 </div>
 <div class="actions">
   <%= f.submit "Cash Deposit" %>
 </div>
<% end %>
<%= link_to 'Back', atm_machine_path(session[:my_atm]),class:"btn btn-danger" %>
</div>

app/views/accounts/new_withdrawal.html.erb
<div class="container">
 <img src=http://i.perezhilton.com/wp-content/uploads/2014/04/moneyy1.gif width="300" height="300">
 <%= form_for @account, url: create_withdrawal_account_path, method: :post do |f| %>
 <div class="field">
   <h1><%= f.label "Withdraw Amount" %></h1><br>
   <%= f.text_field :amount %>
 </div>
 <div class="actions">
   <%= f.submit "Cash Withdrawal" %>
 </div>
<% end %>
<%= link_to 'Back', atm_machine_path(session[:my_atm]),class:"btn btn-danger" %>
</div>

app/views/accounts/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Account no:</strong>
  <%= @account.account_no %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @account.balance %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>
</div>